server:
  port: 8080
  servlet:
    context-path: /QuanLyVuaCa

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/QuanLyVuaCa"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        # Dòng này quan trọng: Bắt Hibernate dùng đúng tên trong @Column, không tự sửa thành snake_case
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
jwt:
  signerKey: "61b8e4c9638f759c9112471bdfff29f02310f0e6e1053fa9c04d924d3d9869fc"
  valid-duration: 3600  #Second - 1 hour
  refreshable-duration: 360000 #Second - 1000 hours