server:
  port: 8080
  servlet:
    context-path: /QuanLyVuaCa

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/QuanLyVuaCa"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

