server:
  port: 8080
  servlet:
    context-path: /QuanLyVuaCa

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/QuanLyVuaCa"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        # Dòng này cực kỳ quan trọng: Bảo Hibernate dùng đúng tên trong @Table
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

